### ISSUE TITLE
Scanning of wifi networks (`wifi-wand a`) no longer works following the airport command deprecation.

### ISSUE THREAD

**Issue by arnlen** [keithrbennett/wifiwand#24]
Apple has officially retired the airport command-line utility on macOS Sonoma 14.4 (see [this post](https://www.intuitibits.com/2024/03/14/goodbye-airport/#:~:text=Apple%20has%20officially%20retired%20the,about%20nearby%20Wi%2DFi%20networks.))

Since the scan feature was relaying on airport ([source code](https://github.com/keithrbennett/wifiwand/blob/main/lib/wifi-wand/models/mac_os_model.rb#L149)), it's now broken. 😢

## Current behavior

```sh
$ wifi-wand a
Available networks are:

[]
```

## Expected behavior

As per Apple recommandation, we should now use the [wdutil](https://real-world-systems.com/docs/wdutil.1.html) command line tool.
Unfortunately, since scanning isn't available (yet?) with wdutil, fixing this issue won't be as easy as switching to the new tool...

## Related issues

Many people are currently fighting to find a workaround 💪 

- https://github.com/gopro/OpenGoPro/issues/506
- https://github.com/ronaldoussoren/pyobjc/issues/600
- https://forums.developer.apple.com/forums/thread/748518

**Comment by keithrbennett** [comment]
Using Swift scripts and the Mac OS CoreWLAN subsystem, I have just restored (in version 2.16.1) the following functions of `wifiwand` disabled due to the `airport` deprecation:

* a[vail_nets]              - array of names of the available networks
* d[isconnect]              - disconnects from current network, does not turn off wifi

An added benefit is that the disconnect task no longer requires sudo access.

However, the CoreWLAN functionality on which the Swift scripts rely is only available if XCode is installed.

Please let me know if you have any issues.

**Comment by VladislavGatsenko** [comment]
I was looking for a solution to a different problem, but maybe this will help with a another solution. Just execute in the console:

system_profiler SPAirPortDataType

**Comment by keithrbennett** [comment]
@arnlen I forgot to thank you for posting this issue, especially so clearly and thoroughly. Thank you!

@VladislavGatsenko Thank you too for your suggestion to use `system_profiler SPAirPortDataType`. It would avoid the need to have XCode installed, and given that there is a JSON output option, would be straightforward to implement. I am currently experimenting with it and will probably use it in wifiwand.

I will close this issue now (as I should have done a long time ago) but let me know if the problem recurs.
